# Generated by Django 4.1.5 on 2023-02-08 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("check_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="inspection",
            name="itemslist",
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
