# Generated by Django 4.1.5 on 2023-02-09 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("check_app", "0003_alter_inspection_manufacturermodel_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inspection",
            name="manufacturerModel",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
    ]
