# Generated by Django 4.1.5 on 2023-02-10 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("check_app", "0004_alter_inspection_manufacturermodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inspection",
            name="checkDetail",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="inspection",
            name="checkTarget",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="inspection",
            name="manufacturerModel",
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="inspection",
            name="method",
            field=models.CharField(blank=True, default="", max_length=50, null=True),
        ),
    ]
